/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Surfaces
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#20201f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353535',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#e3bfb3',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#aa897f',
        'outline-variant': '#5b4138',
        'surface-tint': '#ffb59c',
        background: '#131313',
        'on-background': '#e5e2e1',
        'surface-variant': '#353535',

        // Primary (Neon Orange)
        primary: '#ffb59c',
        'on-primary': '#5c1900',
        'primary-container': '#ff5f1f',
        'on-primary-container': '#561700',
        'inverse-primary': '#ab3600',
        'primary-fixed': '#ffdbcf',
        'primary-fixed-dim': '#ffb59c',
        'on-primary-fixed': '#390c00',
        'on-primary-fixed-variant': '#832700',

        // Secondary (Emerald Green)
        secondary: '#66dd8b',
        'on-secondary': '#003919',
        'secondary-container': '#25a55a',
        'on-secondary-container': '#003115',
        'secondary-fixed': '#83fba5',
        'secondary-fixed-dim': '#66dd8b',
        'on-secondary-fixed': '#00210c',
        'on-secondary-fixed-variant': '#005227',

        // Tertiary (Neutral Grey)
        tertiary: '#c8c6c5',
        'on-tertiary': '#313030',
        'tertiary-container': '#959393',
        'on-tertiary-container': '#2d2c2c',
        'tertiary-fixed': '#e5e2e1',
        'tertiary-fixed-dim': '#c8c6c5',
        'on-tertiary-fixed': '#1c1b1b',
        'on-tertiary-fixed-variant': '#474646',

        // Error
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        sora: ['Sora', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        'display-lg': ['Sora', 'sans-serif'],
        'headline-lg': ['Sora', 'sans-serif'],
        'headline-lg-mobile': ['Sora', 'sans-serif'],
        'headline-md': ['Sora', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Sora', 'sans-serif'],
        caption: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '16px',
        'margin-mobile': '20px',
        'margin-desktop': '120px',
        'container-margin': '32px',
        'card-padding': '24px',
        'section-gap': '32px',
      },
      boxShadow: {
        'neon-orange': '0 0 15px rgba(255, 95, 31, 0.4)',
        'neon-emerald': '0 0 15px rgba(102, 221, 139, 0.4)',
        'neon-orange-sm': '0 0 8px rgba(255, 95, 31, 0.5)',
        'neon-emerald-sm': '0 0 8px rgba(102, 221, 139, 0.5)',
      },
      backdropBlur: {
        xs: '2px',
      },
      keyframes: {
        scan: {
          '0%, 100%': { transform: 'translateY(0%)' },
          '50%': { transform: 'translateY(2000%)' },
        },
      },
      animation: {
        scan: 'scan 2.5s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
