/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Olive & Warm Earth Palette
        primary: '#7C8C3D',
        'on-primary': '#FFFFFF',
        'primary-container': '#8FA34D',
        'on-primary-container': '#FFFFFF',
        'primary-fixed': '#D4E8A0',
        'primary-fixed-dim': '#B8CC7A',
        'on-primary-fixed': '#2A3310',
        'on-primary-fixed-variant': '#4A5D23',
        'inverse-primary': '#A8B87A',

        secondary: '#EDE0D4',
        'on-secondary': '#3D3228',
        'secondary-container': '#D4C5A9',
        'on-secondary-container': '#3D3228',
        'secondary-fixed': '#FFF0E0',
        'secondary-fixed-dim': '#EDE0D4',
        'on-secondary-fixed': '#2A221C',

        tertiary: '#C5BAAA',
        'on-tertiary': '#3D3228',
        'tertiary-container': '#A69885',
        'on-tertiary-container': '#2A221C',

        // Surfaces
        surface: '#1E201B',
        'surface-dim': '#1A1C17',
        'surface-bright': '#3D4033',
        'surface-container-lowest': '#161812',
        'surface-container-low': '#24261F',
        'surface-container': '#282A22',
        'surface-container-high': '#32352B',
        'surface-container-highest': '#3D4033',
        'on-surface': '#EDE0D4',
        'on-surface-variant': '#C5BAAA',
        'inverse-surface': '#EDE0D4',
        'inverse-on-surface': '#2A2A2A',
        outline: '#A69885',
        'outline-variant': '#5C5246',
        background: '#181A15',
        'on-background': '#EDE0D4',
        'surface-variant': '#32352B',

        // Error (warm clay)
        error: '#D4866F',
        'on-error': '#FFFFFF',
        'error-container': '#B0604A',
        'on-error-container': '#FFFFFF',
      },
      fontFamily: {
        sora: ['Sora', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        'display-lg': ['Sora', 'sans-serif'],
        'headline-lg': ['Sora', 'sans-serif'],
        'headline-lg-mobile': ['Sora', 'sans-serif'],
        'headline-md': ['Sora', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Sora', 'sans-serif'],
        caption: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '16px',
        'margin-mobile': '20px',
        'margin-desktop': '120px',
        'container-margin': '32px',
        'card-padding': '24px',
        'section-gap': '32px',
      },
      boxShadow: {
        warm: '0 4px 20px rgba(124, 140, 61, 0.15)',
        'warm-sm': '0 2px 8px rgba(124, 140, 61, 0.12)',
        'warm-lg': '0 8px 40px rgba(124, 140, 61, 0.2)',
        cream: '0 4px 20px rgba(237, 224, 212, 0.1)',
        'cream-lg': '0 8px 40px rgba(237, 224, 212, 0.15)',
        soft: '0 4px 24px rgba(0, 0, 0, 0.25)',
        'soft-lg': '0 8px 48px rgba(0, 0, 0, 0.35)',
      },
      backdropBlur: {
        xs: '2px',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'slide-down': {
          '0%': { opacity: '0', transform: 'translateY(-12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        pulse: {
          '0%, 100%': { opacity: '0.6' },
          '50%': { opacity: '1' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.5s ease-out',
        'fade-in-up': 'fade-in-up 0.6s ease-out',
        'scale-in': 'scale-in 0.3s ease-out',
        'slide-down': 'slide-down 0.3s ease-out',
        shimmer: 'shimmer 2s ease-in-out infinite',
        'pulse-soft': 'pulse 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
